[[binary-functions-list]]

[cols="1,1,1,1"]
|===

| link:#base[base] | link:#color[color] | link:#frac[frac] | link:#inf[inf]

| link:#lim[lim] | link:#log[log] | link:#mod[mod] | link:#over[over]

| link:#overset[overset] | link:#power[power] | link:#root[root] | link:#script[script]

| link:#semantics[semantics] | link:#stackrel[stackrel] | link:#substack[substack] | link:#underset[underset]

|===


= Binary functions Examples

[[base]]

== Base
* **AsciiMath**
```
x_(y)
```
* **LaTeX**
```
x_{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <msub>
      <mi>x</mi>
      <mi>y</mi>
    </msub>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:sSub>
      <m:sSubPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:sSubPr>
      <m:e>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:e>
      <m:sub>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:sub>
    </m:sSub>
  </m:oMath>
</m:oMathPara>
```

[[color]]

== Color
* **AsciiMath**
```
color(red)(y)
```
* **LaTeX**
```
{\color{red} y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mstyle mathcolor="red">
      <mi>x</mi>
    </mstyle>
  </mstyle>
</math>
```

NOTE: In other conversions, the value of the class will be processed as a simple text. For example, the output of this example in *AsciiMath* will be represented as `x`.

[[frac]]

== Frac
* **AsciiMath**
```
frac(x)(y)
```
* **LaTeX**
```
\frac{x}{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mfrac>
      <mi>x</mi>
      <mi>y</mi>
    </mfrac>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:f>
      <m:fPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:fPr>
      <m:num>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:num>
      <m:den>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:den>
    </m:f>
  </m:oMath>
</m:oMathPara>
```

[[inf]]

== Inf
* **AsciiMath**
```
inf_(x)^(y)
```
* **LaTeX**
```
\inf_{x}^{y}
```

NOTE: In other conversions, the generated output will resemble the content in the link:#underover[underover class]

[[lim]]

== Lim
* **AsciiMath**
```
lim_(x)^(y)
```
* **LaTeX**
```
\lim_{x}^{y}
```

NOTE: In other conversions, the generated output will resemble the content in the link:#underover[underover class]

[[log]]

== Log
* **AsciiMath**
```
log_(x)^(y)
```
* **LaTeX**
```
\log_{x}^{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <msubsup>
      <mi>log</mi>
      <mi>x</mi>
      <mi>y</mi>
    </msubsup>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:sSubSup>
      <m:sSubSupPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:sSubSupPr>
      <m:e>
        <m:r>
          <m:rPr>
            <m:sty m:val="p"/>
          </m:rPr>
          <m:t>log</m:t>
        </m:r>
      </m:e>
      <m:sub>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:sub>
      <m:sup>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:sup>
    </m:sSubSup>
  </m:oMath>
</m:oMathPara>
```

[[mod]]

== Mod
* **AsciiMath**
```
x mod y
```
* **LaTeX**
```
{x} \mod {y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mrow>
      <mi>x</mi>
      <mi>mod</mi>
      <mi>y</mi>
    </mrow>
  </mstyle>
</math>
```

NOTE: In other conversions, the value of the class will be processed as a simple text. For example, the *presentation* of this example in *OMML*  will be `"x" rm( mod ) "y"`.

[[over]]

== Over
* **LaTeX**
```
{x \over y}
```

NOTE: In other conversions, the generated output will resemble the content in the link:#frac[Frac class]

[[overset]]

== Overset
* **AsciiMath**
```
overset(x)(y)
```
* **LaTeX**
```
\overset{x}{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mover>
      <mi>y</mi>
      <mi>x</mi>
    </mover>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:limUpp>
      <m:limUppPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:limUppPr>
      <m:e>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:e>
      <m:lim>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:lim>
    </m:limUpp>
  </m:oMath>
</m:oMathPara>
```

[[power]]

== Power
* **AsciiMath**
```
x^(y)
```
* **LaTeX**
```
x^{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <msup>
      <mi>x</mi>
      <mi>y</mi>
    </msup>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:sSup>
      <m:sSupPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:sSupPr>
      <m:e>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:e>
      <m:sup>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:sup>
    </m:sSup>
  </m:oMath>
</m:oMathPara>
```

[[root]]

== Root
* **AsciiMath**
```
root(x)(y)
```
* **LaTeX**
```
\sqrt[x]{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mroot>
      <mi>y</mi>
      <mi>x</mi>
    </mroot>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:rad>
      <m:radPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:radPr>
      <m:deg>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:deg>
      <m:e>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:e>
    </m:rad>
  </m:oMath>
</m:oMathPara>
```

[[semantics]]

== Semantics
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <semantics>
      <mi>x</mi>
      <annotation>
        <mi>MathType@MTEF@5@5@+= feaagKart1ev2aaatCvAUfeBSjuyZL2yd9gzLbvyNv2CaerbbjxAHX garuavP1wzZbItLDhis9wBH5garmWu51MyVXgarqqtubsr4rNCHbGe aGqipG0dh9qqWrVepG0dbbL8F4rqqrVepeea0xe9LqFf0xc9q8qqaq Fn0lXdHiVcFbIOFHK8Feea0dXdar=Jb9hs0dXdHuk9fr=xfr=xfrpe WZqaaeaaciWacmGadaGadeaabaGaaqaaaOqaamaapedabaGaamOzai aacIcacaWG0bGaaiykaKqzaeGaaiizaOGaamiDaaWcbaGaamiDamaa BaaameaacaaIYaaabeaaaSqaaiaadshadaWgaaadbaGaaGymaaqaba aaniabgUIiYdaaaa@40DD@ </mi>
      </annotation>
    </semantics>
  </mstyle>
</math>
```

NOTE: In other conversions, the value of the class will be processed as a simple text. For example, the output of this example in *AsciiMath* will be represented as `x`.

[[stackrel]]

== Stackrel
* **AsciiMath**
```
stackrel(x)(y)
```
* **LaTeX**
```
\stackrel{x}{y}
```

NOTE: In other conversions, the generated output will resemble the content in the link:#overset[Overset class]

[[underset]]

== Underset
* **AsciiMath**
```
underset(x)(y)
```
* **LaTeX**
```
\underset{x}{y}
```
* **MathML**
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <munder>
      <mi>y</mi>
      <mi>x</mi>
    </munder>
  </mstyle>
</math>
```
* **OMML**
```
<m:oMathPara>
  <m:oMath>
    <m:limLow>
      <m:limLowPr>
        <m:ctrlPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
            <w:i/>
          </w:rPr>
        </m:ctrlPr>
      </m:limLowPr>
      <m:e>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:e>
      <m:lim>
        <m:r>
          <m:t>y</m:t>
        </m:r>
      </m:lim>
    </m:limLow>
  </m:oMath>
</m:oMathPara>
```
