---
layout: post
title:  "Using Plurimath"
date:   2023-08-22 00:00:00 +0800
categories:
  - plurimath
  - using
authors:
  -
    name: Suleman Uzair
    email: sulemanuzair600@gmail.com
    social_links:
      - https://github.com/suleman-uzair/
  -
    name: Ronald Tse
    email: tse@ribose.com
    use_picture: assets
    social_links:
      - https://www.linkedin.com/in/rhtse/
      - https://github.com/ronaldtse
excerpt: >-
  Conversions across multiple representational languages is a core feature of Plurimath.
  To make it even more accessible, you can easily perform conversions by specifying the input string's type.
---

= Using Plurimath

== What is Plurimath?

*Plurimath* is a comprehensive and efficient tool that enhances the way mathematical content is converted between different formats.
It is designed to work with various markup languages such as *MathML*, *LaTeX*, *AsciiMath*, and *OMML*, making it a versatile and adaptable tool.

One significant advantage is that users don't have to deal with the inconvenience of installing and managing multiple libraries for these different languages. *Plurimath* encompasses them all within a single solution.

This approach simplifies and improves the process of converting mathematical content between markup languages, making it easier and more reliable.

== 1. How to use Plurimath?

Using *Plurimath* is straightforward and user-friendly, whether you're working on a *Ruby* application, a *Ruby on Rails* project, or any other framework based on *Ruby*.
To get started, add this line into your applications gemfile.
add this line into your applications gemfile

```ruby
  gem "plurimath"
```
then run following command
```ruby
  bundle install
```
or run following command
```ruby
  gem install plurimath
```

Once it's incorporated, you can seamlessly convert mathematical expressions between various markup languages.

=== 1.1 Understanding Plurimath

*Plurimath* provides a range of conversion methods, allowing you to specify the input type and obtain the desired output format.
With just a few lines of code, you can harness the power of *Plurimath* to ensure consistency and compatibility in mathematical presentations across different platforms and applications.

Now let's discuss *how to use Plurimath?*.

```ruby
  formula = Plurimath::Math.parse(string, :type)
```

You will have to provide input text replacing `string`, and the `type` field should specify the type of the provided text, choosing from one of the supported languages.

The above example will generate a Formula object, something like this

```ruby
  Plurimath::Math::Formula.new([
    ... # Others objects
  ])
```

Now the next step would be conversion (since you have parsed your string into a *Plurimath Formula*) to your desired output format. For conversion all you have to do is call the method name containing the format name with a leading `to_`.

```ruby
  formula.to_<language-name>
```
or you can do it directly,
```ruby
  Plurimath::Math.parse(string, :type).to_<language-name>
```

NOTE: Some methods support explicit optional argument and some don't.

The sections below will explain each supported languages conversion and parsing with an example

=== 1.2 Use of Plurimath, Explained

The sections below will help you understand using *Plurimath* with a real worked example.
We have an *AsciiMath* equation `sum_(i=1)^n i^3`, we will be using this equation in all the sections.

==== 1.2.1 AsciiMath to Formula

```ruby
  input_string = 'sum_(i=1)^n i^3'
  formula = Plurimath::Math.parse(input_string, :asciimath)
```
Parsing the equation will generate the following formula.
```ruby
  Plurimath::Math::Formula.new([
    Plurimath::Math::Function::Sum.new(
      Plurimath::Math::Formula.new([
        Plurimath::Math::Symbol.new("i"),
        Plurimath::Math::Symbol.new("="),
        Plurimath::Math::Number.new("1")
      ]),
      Plurimath::Math::Symbol.new("n"),
      Plurimath::Math::Function::Power.new(
        Plurimath::Math::Symbol.new("i"),
        Plurimath::Math::Number.new("3")
      )
    )
  ])
```

==== 1.2.2 Formula to AsciiMath

The following example follows the same steps we have before for *AsciiMath* as well.

```ruby
  input_string = <<~MATHML
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mstyle displaystyle="true">
        <mrow>
          <munderover>
            <mo>&#x2211;</mo>
            <mrow>
              <mi>i</mi>
              <mo>=</mo>
              <mn>1</mn>
            </mrow>
            <mi>n</mi>
          </munderover>
          <msup>
            <mi>i</mi>
            <mn>3</mn>
          </msup>
        </mrow>
      </mstyle>
    </math>
  MATHML
  formula = Plurimath::Math.parse(input_string, :mathml)
  formula.to_asciimath # >> "sum_(i=1)^n i^3"
```

*AsciiMath* grammar is different than other languages.
The list of symbols and presentations available in *AsciiMath* is limited compared to other languages, and there is variability between different software in what symbols they support. Metanorma has drawn on Asciidoctor Asciimath in its implementation.

You can see the list of symbols, classes and presentations available in Metanorma's version of *AsciiMath* at https://github.com/plurimath/plurimath/blob/main/MathML-Supported-Data.adoc[Supported *AsciiMath* Data].

==== 1.2.3 Formula to MathML

A Formula object can be converted to *MathML* using the `to_mathml` method.

```ruby
formula.to_mathml
```
This will generate following output of *MathML*

```ruby
  <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <mstyle displaystyle="true">
      <mrow>
        <munderover>
          <mo>&#x2211;</mo>
          <mrow>
            <mi>i</mi>
            <mo>=</mo>
            <mn>1</mn>
          </mrow>
          <mi>n</mi>
        </munderover>
        <msup>
          <mi>i</mi>
          <mn>3</mn>
        </msup>
      </mrow>
    </mstyle>
  </math>
```

In *MathML* we have the *displaystyle* boolean attribute, making the equation `normal` or `compact`.
By default we use `display_style` true, but you can explicitly change it by passing `display_style:` argument to `to_mathml` method, depending on what output you desire.
See examples below.

```ruby
  formula.to_mathml(display_style: false)
  formula.to_mathml(display_style: true)
```
NOTE: *display_style* will affect the whole Formula equation and not any specific tag or part of the equation.

NOTE: You can pass *display_style* attribute within the string argument, but it has to be set at the top-level `mstyle` tag, as shown in the example above.

You can see the list of https://github.com/plurimath/plurimath/blob/main/MathML-Supported-Data.adoc[*MathML* Supported Data] such as symbols, tags and functions.

==== 1.2.4 Latex to AsciiMath

Example of parsing and conversion for *LaTeX* below.

```ruby
  input_string = "\\prod_{\\theta}^{100}"
  formula = Plurimath::Math.parse(input_string, :latex)
  formula.to_asciimath # >> "sum_(i=1)^n i^3"
```

*LaTeX* encompasses an extensive array of symbols and functions, catering to various mathematical expressions.

We support a comprehensive list of these functions and symbols, which you can see at https://github.com/plurimath/plurimath/blob/main/Latex-Supported-Data.adoc[Supported *LaTeX* Data].


==== 1.2.5 OMML to AsciiMath

Processing the OMML example below will also follow the same steps.

```ruby
  input_string = <<~OMML
    <m:oMathPara xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
      <m:oMath>
        <m:nary>
          <m:naryPr>
            <m:chr m:val="∑"/>
            <m:limLoc m:val="undOvr"/>
            <m:subHide m:val="0"/>
            <m:supHide m:val="0"/>
          </m:naryPr>
          <m:sub>
            <m:r>
              <m:t>i</m:t>
            </m:r>
            <m:r>
              <m:t>=</m:t>
            </m:r>
            <m:r>
              <m:t>1</m:t>
            </m:r>
          </m:sub>
          <m:sup>
            <m:r>
              <m:t>n</m:t>
            </m:r>
          </m:sup>
          <m:e>
            <m:sSup>
              <m:sSupPr>
                <m:ctrlPr>
                  <w:rPr>
                    <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
                    <w:i/>
                  </w:rPr>
                </m:ctrlPr>
              </m:sSupPr>
              <m:e>
                <m:r>
                  <m:t>i</m:t>
                </m:r>
              </m:e>
              <m:sup>
                <m:r>
                  <m:t>3</m:t>
                </m:r>
              </m:sup>
            </m:sSup>
          </m:e>
        </m:nary>
      </m:oMath>
    </m:oMathPara>
  OMML
  formula = Plurimath::Math.parse(input_string, :omml)
  formula.to_asciimath # >> "sum_(\"i\" = 1)^(\"n\") \"i\"^(3)"
```

We also support *OMML*, allowing you to work with mathematical content efficiently in *Office* documents.

==== 1.2.6 Formula to OMML

The Formula object can be converted to *OMML* using `to_omml` method.

`formula.to_omml(display_style: false)`

NOTE: `display_style: false` can be omitted in the above example because it 'false' by default. So, formula.to_omml is equivalent to above example

NOTE: *MathML* string supports *displaystyle* but *OMML* don't have any one attribute or tag corresponding to it. So in order to get the same effect of normal vs compact rendering of equations, you will have to pass the `display_value` argument explicitly to the *OMML* rendering request, as `to_omml(display_style: (true or false))`


This will generate following output of *OMML*

```ruby
<m:oMathPara xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
  <m:oMath>
    <m:nary>
      <m:naryPr>
        <m:chr m:val="∑"/>
        <m:limLoc m:val="undOvr"/>
        <m:subHide m:val="0"/>
        <m:supHide m:val="0"/>
      </m:naryPr>
      <m:sub>
        <m:r>
          <m:t>i</m:t>
        </m:r>
        <m:r>
          <m:t>=</m:t>
        </m:r>
        <m:r>
          <m:t>1</m:t>
        </m:r>
      </m:sub>
      <m:sup>
        <m:r>
          <m:t>n</m:t>
        </m:r>
      </m:sup>
      <m:e>
        <m:sSup>
          <m:sSupPr>
            <m:ctrlPr>
              <w:rPr>
                <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
                <w:i/>
              </w:rPr>
            </m:ctrlPr>
          </m:sSupPr>
          <m:e>
            <m:r>
              <m:t>i</m:t>
            </m:r>
          </m:e>
          <m:sup>
            <m:r>
              <m:t>3</m:t>
            </m:r>
          </m:sup>
        </m:sSup>
      </m:e>
    </m:nary>
  </m:oMath>
</m:oMathPara>
```
