---
layout: post
title:  "Font coverage of Unicode math"
date:   2023-08-15 00:00:00 +0800
categories:
  - plurimath
  - introduction
authors:
  -
    name: Alexander Dyuzhev
    email: dyuzhev@gmail.com
    social_links:
      - https://www.linkedin.com/in/alexander-dyuzhev/
      - https://github.com/Intelligent2013/
  -
    name: Ronald Tse
    email: tse@ribose.com
    social_links:
      - https://github.com/ronaldtse


excerpt: >-
    Pluramath supports all latex-accessible math constants. Math fonts
    have different support of math glyphs.
---

:page-liquid:

== Font coverage of Unicode math

The one of main goals for any math representation formats is displaying.
There are a few typical math fonts that contain the big set of mathematical symbols:

* Cambria Math

* STIX Two Math

* Noto Math

* Libertinus Math

When people / SDOs choose one of these fonts, they need to know what math symbols are 
available and which ones are not.

Each font has own set of supported glyphs. We have compared the sets of the mathematical 
glyphs from these four fonts and get the results. The sets of glyphs based on Pluramath's
latex-accessible math constants
(determined in https://github.com/plurimath/plurimath/blob/main/lib/plurimath/latex/constants.rb).

We'used these versions of the fonts:

* Cambria Math (v6.99, July 7, 2019), from Windows 10

* STIX Two Math (v2.13 b171, May 26, 2021), https://github.com/stipub/stixfonts/releases/tag/v2.13b171

* Noto Sans Math (v2.0001, Nov, 19, 2020), https://fonts.google.com/download?family=Noto%20Sans%20Math

* Libertinus Math (v7.040, Feb 26, 2021), https://github.com/alerque/libertinus/releases/tag/v7.040

We have compared four math fonts on what glyphs are supported. 


[cols="a,a,a,a,a,a"]
|===
| LaTeX symbol name | Unicode character code | STIX Two Math | Cambria Math | Noto Sans Math | Libertinus Math

{% for symbol in site.data.2023-08-15-font_coverage.symbols %}


| `{{ symbol.latex_symbol_name }}` | `{{ symbol.unicode_char_code | escape_once }}` 

{% assign stixtwomath_font = symbol.fonts | where: "font_name", "STIX Two Math" | first %}
{% assign cambriamath_font = symbol.fonts | where: "font_name", "Cambria Math" | first %}
{% assign notosansmath_font = symbol.fonts | where: "font_name", "Noto Sans Math" | first %}
{% assign libertinusmath_font = symbol.fonts | where: "font_name", "Libertinus Math" | first %}

| {% if stixtwomath_font.support %}✅{% else %}❌{% endif %} 
| {% if cambriamath_font.support %}✅{% else %}❌{% endif %} 
| {% if notosansmath_font.support %}✅{% else %}❌{% endif %} 
| {% if libertinusmath_font.support %}✅{% else %}❌{% endif %} 

{% endfor %}

|===


[NOTE]
====
* Cambria Math - 176 missing glyphs

* STIX Two Math - 3 missing glyphs

* Noto Sans Math - 321 missing glyphs

* Libertinus Math - 792 missing glyphs

Missing glyphs in all fonts:

* arrowbullet 0x27a2
* ballotx 0x2717
* pencil 0x270e

====

You can find the rendered PDF with
glyphs for each font link:/assets/blog/2023-08-15_plurimath_latex_constants.pdf[here]. 
Note: the character '#' means 'glyph is not available in font' (except number sign U+0023 char).


== Conclusion

The font STIX Two Math has the fullest math support.
