---
layout: post
title:  "Number formatting in all supported conversions"
date:   2024-09-17 00:00:00 +0800
categories:
  - plurimath
  - introduction
author:
  name: Ronald Tse
  email: tse@ribose.com
  use_picture: assets
  social_links:
    - https://www.linkedin.com/in/rhtse/
    - https://github.com/ronaldtse
excerpt: >-
  Plurimath now supports number formatting in all supported conversions.
---

== Why number formatting in all supported conversions?

Number formatting support in **Plurimath** as an individual feature is crucial for users who need to work with numbers exclusively. However, managing numbers within a **Plurimath Formula** has been challenging. We are thrilled to announce that number formatting is now supported in **Plurimath Formula**, enabling users to handle numbers more efficiently and effortlessly.

IMPORTANT: Understand and discover how to effectively use the **Number Formatting** feature by visiting our detailed guide here: link:../2024-07-09-number-formatter[Number Formatter Support].

== How to use?

To utilize number formatting in all supported conversions within **Plurimath**, simply pass a **Plurimath::Formatter** object to the `formatter` option. **Plurimath** offers a standard formatter class, **Plurimath::Formatter::Standard**, which includes a comprehensive link:#standard_configuration[standard configuration] for seamless number formatting.

.Syntax of using a `Plurimath::Formatter::Standard` object in `Formula` to `LaTeX` conversion
[source,ruby]
----
formatter = Plurimath::Formatter::Standard.new
formula = Plurimath::Math.parse('\sum_{i=1}^{10000} i^2121221', :latex)
formula.to_latex(formatter: formatter) # => '\sum_{i = 1}^{10,000} i^{2,121,221}'
----

Formatting configuration can be changed by:

1. Creating your own custom formatter inherited from `Plurimath::Formatter::Standard` class.
2. Passing options to the `Plurimath::Formatter::Standard` class initializer (options explained in the link:../2024-07-09-number-formatter[Number Formatter Support blog post]).

=== 1. Creating a Custom Formatter

Having a custom formatter is useful when you want to apply formatting configuration different than the **Standard** class to the numbers or need multiple formatting configurations for different parts of your document.

Let's create a formatter `Plurimath::Formatter::CustomFrFormatter` with `fr` locale as an example.

.Syntax of creating a custom formatter
[source,ruby]
----
class CustomFrFormatter < Plurimath::Formatter::Standard
  def initialize(locale: :fr)
    super
  end
end
----

NOTE: The `en` locale will be used as the default if it's not specified or supported.

Add the `DEFAULT_OPTIONS` constant with the desired configuration in the `CustomFrFormatter` class.

.Syntax to set the `DEFAULT_OPTIONS` constant in the `CustomFrFormatter` class
[source,ruby]
----
class CustomFrFormatter < Plurimath::Formatter::Standard
  DEFAULT_OPTIONS = {
    fraction_group_digits: 2,
    fraction_group: ".",
    ...
  }.freeze

  def initialize(locale: :fr)
    super
  end
end
----

Or just override the `set_default_options` method to set the default options.

.Syntax to override the `set_default_options` method
[source,ruby]
----
class CustomFrFormatter < Plurimath::Formatter::Standard
  def initialize(locale: :fr)
    super
  end

  def set_default_options(options = {})
    options = {
      fraction_group_digits: 2,
      ...
    }
  end
end
----

NOTE: The `initialize` method is used to set the locale only in our example.

TIP: You can configure the formatter by either using the `set_default_options` method or defining the `DEFAULT_OPTIONS` constant. Both approaches allow you to set the necessary values for the formatter.

.Creating a `CustomFormatter` object and using it to format numbers in a formula
[example]
====
[source,ruby]
----
class CustomFormatter < Plurimath::Formatter::Standard
  DEFAULT_OPTIONS = {
    fraction_group_digits: 2,
    fraction_group: ".",
    group_digits: 2,
    decimal: ";",
    group: ",",
  }.freeze

  def initialize(locale: :hy) # randomly picked a locale from the list of supported locales
    super
  end
end

formula = Plurimath::Math.parse('\sum_{i=1}^{1000.001} i^2121221.3434', :latex)
formula.to_latex(formatter: formatter) # => '\sum_{i = 1}^{10,00;00.1} i^{2,12,12,21;34.34}'
----
====

=== 2. Changing Standard Configuration

`Plurimath::Formatter::Standard` class initializer accepts four arguments to set the options values.
Arguments are:

* `locale: # a symbol or string value`
* `options: # a hash of options (localizer_symbols)`
* `format_string: # a string value (localize_number)`
* `precision: # an integer value`

.Passing arguments to the `Plurimath::Formatter::Standard` class initializer
[source,ruby]
----
options = {
  fraction_group_digits: 2,
  fraction_group: ".",
  group_digits: 2,
  decimal: ";",
  group: ",",
}
formatter = Plurimath::Formatter::Standard.new(locale: :hy, options: options, precision: 2) # format_string: <string value> if provided
Plurimath::Math.parse('2121221.3434', :latex).to_latex(formatter: formatter) # => '2,12,12,21;34'
----

NOTE: Precision option in the initializer overrides it's value specified in the constant.

[[standard_configuration]]
==== Standard Configuration

The `Plurimath::Formatter::Standard` class contains the standard configuration for formatting numbers.

.Default values of options in `Plurimath::Formatter::Standard` class
[source,ruby]
----
  fraction_group_digits = 3
  exponent_sign = "plus"
  fraction_group = "'"
  notation = :basic
  group_digits = 3
  significant = 0
  digit_count = 0
  precision = 0
  decimal = "."
  group = ","
  times = "x"
  e = "e"
----

.Default values of arguments in `Plurimath::Formatter::Standard` class
[source,ruby]
----
  locale = :en
  options = {}
  format_string = nil
  precision = nil
----
